// sim_main.cpp
#include <verilated.h>
#include "Vhalf_adder_tb.h"          // generated by Verilator
#include "verilated_vcd_c.h"         // for waveform dumping

int main(int argc, char **argv) {
  Verilated::commandArgs(argc, argv);
  Vhalf_adder_tb* tb = new Vhalf_adder_tb;
  VerilatedVcdC* tfp = new VerilatedVcdC;
  tb->trace(tfp, 99);
  tfp->open("sim.vcd");

  // simple clock loop until $finish is called
  for (vluint64_t tick = 0; !Verilated::gotFinish(); ++tick) {
    tb->clk = (tick & 1);
    tb->eval();
    tfp->dump(10*tick);
  }

  tfp->close();
  delete tb;
  delete tfp;
  return 0;
}
