
name: Icarus Verilog Simulation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  icarus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Icarus Verilog
        run: |
          sudo apt update
          sudo apt install -y iverilog

      - name: Run Icarus Testbenches
        run: |
          make ci-icarus
